export const DOMAIN_EVENT_TYPES = [
  "run.created",
  "run.event_recorded",
  "age.advanced",
  "player.choice_selected",
  "player.free_action_attempted",
  "player.talent_added",
  "growth.evidence_added",
  "growth.attribute_layer_changed",
  "growth.exposure_changed",
  "opening.origin_recorded",
  "story.fact_added",
  "story.fact_closed",
  "story.thread_updated",
  "story.axis_updated",
  "story.event_shape_recorded",
  "story.asset_spotlight_recorded",
  "story.experience_recorded",
  "story.curriculum_recorded",
  "story.topic_recorded",
  "story.annual_agenda_recorded",
  "npc.relationship_changed",
  "npc.memory_added",
  "npc.visibility_changed",
  "world.progress_changed",
  "world.flag_added",
  "world.state_changed",
  "ending.reached",
  "memory.added",
  "score.changed",
  "status.changed",
  "faction.changed",
];

export const DOMAIN_EVENT_TYPE_SET = new Set(DOMAIN_EVENT_TYPES);
